### ISSUE TITLE
Kitty cursor inverse

### ISSUE THREAD

**Issue by fladson** [subnut/dotfiles-artix-s6#1]
Hi there.
I found your code to inverse nvim cursor for kitty but it is not working on my config. I just wanted to check with you if it is indeed working as expected so I can debug on my end.

Thanks.

**Comment by subnut** [comment]
Are you using neovim v0.5? Do you have Tree-sitter enabled?

If **yes**, then my code won't work.
If **no**, then please show me the code that you implemented, it seems to be working on my side.
have you have added `let g:kitty_fancy_cursor = 1` in your `init.vim`?

**Comment by subnut** [comment]
I am curious how you found this repo of mine....

**Comment by fladson** [comment]
> Are you using neovim v0.5? Do you have Tree-sitter enabled?

Yes, nice to know. Any tips on how to get it working for that setup? It is the only thing I miss from Alacritty.

I found your code while searching for `guibg inverse kitty` 😄

**Comment by subnut** [comment]
> Yes, nice to know. Any tips on how to get it working for that setup?

Unfortunately, no. 
But if I do ever find it out, I shall report it here. :+1:
